# Generated by Django 4.2 on 2023-05-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=900)),
                ('email', models.CharField(max_length=900)),
                ('message', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.AlterField(
            model_name='chat',
            name='remedy',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='chat',
            name='symptoms',
            field=models.CharField(max_length=100),
        ),
    ]
