# Generated by Django 4.2 on 2023-05-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayuapp', '0005_alter_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
